# Generated by Django 4.2 on 2024-01-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
